travis:
  secure:
    BINSTAR_TOKEN: UP+xBovD0cCpKpnlO7LC51dg2idHsPeuTY1M60J+FVKUha3c+FrsD3uiLVn0GsrRJL9xX9Lls/WVErrn6cOoAF05jFALCl03bpK9N0fAvbYDafk/G1wQoCmAeSKjmfcF6p7G9lngXFYP4dIg9azmXmQlPCy09LM+gt9XIE+N5/W1un42Oc2QEinMjqD38kWeoc53NbYT9MVk0hbHOvRPVpzNd20SkB8wc4PrDpbD1j2DIolvcwmwUV546vvqNoRhymvxzNH2JCJ8QTkOEk0XYczZr/VtEfeHoEyvAy+YnAO/7N7lzWAD3LTc2CdI+tJyb6xQhzW5/hJI+hTsebF5yLLCMWlFtQ9MojaFfq2bUZjXNpjXwRhhllkxPyFE22MaINu/iqJ7AVrO2LoKcSs2YQ11F1j8gX6UOWqa13OMk5WwbxHYqH1kzXJRxGSBqbugF7lnUjDNw1HnqVySJMZEm3N9MmhXZH0UqVqHUbAheGkEGxFJi2R46mkeeTuyVd5eHvuYy5sWyBg91lvrNYBBJRlVrAoZRwcaKw/QaB0i41wtysoyFfKI4QpRw8+uehllCDoTDeX02c4W70shJi/cf15fs7lZ/sYmhvcSeo492qPQ3KoLDcmVbfFsLpfZCQBxAyh9OTy0j838chFfeDRIF3Bvij3X8l4vMWen8jpZHok=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
