travis:
  secure:
    BINSTAR_TOKEN: KZ+z/+MLX1jotV9VnJ7Y0hDcbjZnC1TQ43nFbXCnOtHnWHTuxsg4G72yYefFKjdY8Obyr28yvE6mZmkPWFlAgB7BLShkwRU9nPvoEqiKgpO5YA0bSex1SQqsEfzbLE732/gFusCGjUiry0vR7/sHwFEKWOnBPvsGZaKbGHuMUvzYp6t8PhkcdT/GhugqqMdaOY1L7c5rmEPzLNsnvfcNp34T1zs8BtEHHnSMrjLvulhhdf6CJ8lHAPDlhZ75//N1OH9csK6CJCKkswPG4kC6bOwIyA4i8pM3Ego3uQmhhtwXPfdweNMliejztDISKvXpqAKJ1ZijVpIIGGPTf4utrIHyYbJKyNfpx6KD5cBZ8HG3iUvf9SriwI5Amo3NUkl/vQouKGcV/S2bF5FiKsYahqEBywS7WgWoWuQnQ/FWUGC0kCJY9TxARXuYEgrwNnEF2/zw11t2LkjWNjYYtnM+75j9SgvcPEssX8imrBMaEbTeMecfLMsaUmF1WRnjYImQW8rBJ+7nlzujf+CHfPJWG0nM8bzTJ6eQlTZmpSNaxM4njhKfViBXqa7AnKjERC3kM5pHEWT0Ef9aQt0NoyPQeEQNYyXiPAPU0RC9Qp+G18e55Es1/LwUZcIZzzkjsr/iBfkgEOX0cA83gW77Zy1ZndXg7fallZOevg0rQGXlXRs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
